### ISSUE TITLE
How to run mesapy after compilation

### ISSUE THREAD

**Issue by albertattaxa** [mesalock-linux/mesapy#10]
I successfully ran `make sgx`. Now, how do I run it? Where is the compiled binary?

**Comment by mssun** [comment]
``make sgx`` will output several things: `libpypy`, `libsgx_tlibc_ext`, `libffi`. These are some dependencies MesaPy for SGX relies on. After successfully compiling these dependencies, you can try the `hello_world` example first, which is in the `mesapy/tree/sgx/sgx/examples/hello_world` directory.  Change to the directory and run `make`, a binary named `app` will be generated in the current directory. You can then run this `app` to test MesaPy for SGX. Thanks.

**Comment by albertattaxa** [comment]
Actually, that's not my question. But I figured it out. The entry point is `pypy`.

**Comment by mssun** [comment]
OK, thanks for reaching out. I'm closing this issue.
